### ISSUE TITLE
Remove from F-Droid

### ISSUE THREAD

**Issue by gferraro** [TheCacophonyProject/cacophonometer#100]
As we are using firebase, remove Bird Monitor from F-Droid store

**Comment by IzzySoft** [comment]
When removing from F-Droid, don't forget to update your Readme. The badge is still there and links to a 404 page now. Maybe you want to replace it with [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) – I'm just adding your app back to my repo, where it originally started (oh, you forgot? Now I'm depressed… :see_no_evil:) You can then link the badge [to this URL](https://apt.izzysoft.de/fdroid/index/apk/nz.org.cacophony.birdmonitor), where the app should show up with the next sync tomorrow (in about 20h from now).

That said, an APK with less proprietary elements and no tracking (like, no Crashlytics and no Firebase Analytics) would be much appreciated; I've no idea what you need Firebase for, but I don't expect you can do without or your app would still be with F-Droid.

Thanks!
