### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by clare** [TheCacophonyProject/cacophonometer#11]
If I put in an invalide  group name and device name page then the app fails to register and there is no feedback when it completes.  Then I can move onto the next page of the setup.   I don't think I should be able to move on unless the setup was successful else it is very confusing for the user as I would assume it worked.     

This page also needs the website link for registering in it's "?" help text as the user may not have got the link from the main screen. 

The page should only ever need one one button -register to begin with.   Remove the un register button unless the phone is registered.  

When the phone is registered, remove the edit boxes and change the button to unregister.

**Comment by timhot** [comment]
All suggestions done.
