### ISSUE TITLE
Buttons are hard to read in poor light conditions

### ISSUE THREAD

**Issue by clare** [TheCacophonyProject/cacophonometer#13]
I was setting up the phone with a bright light - similar to outside and I found the midgreen button with black text particularly hard to read.  The white text is slightly better but not great.  I think we need to make sure we have high contrasting colour scheme, so that the app works well out side.  

Also there is a problem with the "OK" on the help screens - I totally didn't see it and couldn't work out how to close this dialog.  It might be more consistent with android gui to have an X at the top right of the dialog.   Make it much bolder as it's really annoying when you don't know how to close it.

**Comment by timhot** [comment]
I've tired a few different colour schemes and settled on pretty much black text on white background with a bit of green tinge when it doesn't affect the readability - see what you think when you see it.

On the help screens, I've made the OK button much larger (couldn't figure out how to put an X on the dialog - this doesn't seem to be the default, so I'm guessing people will be getting used to the OK at the bottom.  

URL on the help screen is also now much more visible.

**Comment by mjs** [comment]
Black text on a white background is good choice. It seems like this issue has been addressed now. Can this ticket be closed?

**Comment by timhot** [comment]
What's the protocol for closing?  Can I, or should it be Clare as she created the issue?

**Comment by mjs** [comment]
You can absolutely close it if you're sure this has been deal with. 

As an old manager of mine used to say, "you are a change agent" :stuck_out_tongue:
