### ISSUE TITLE
Dialogs don't work when phone is sideways. 

### ISSUE THREAD

**Issue by clare** [TheCacophonyProject/cacophonometer#14]
So either forbid the app changing orientation or make sure it looks ok.

**Comment by timhot** [comment]
I've reworked the app, so not sure if I can reproduce what you saw.  But now, if the phone is rotated, the help dialog closes, but can be reopened easily enough and displays OK.

**Comment by timhot** [comment]
Have now also added android:screenOrientation="portrait" to each activity to prevent landscape mode
