### ISSUE TITLE
Automatic Gain Control on or off

### ISSUE THREAD

**Issue by ionise** [TheCacophonyProject/cacophonometer#16]
When reviewing the recordings that have been uploaded to the API the low level ambient noise appears to be clipped and only loud sounds are heard. 
It seems as though the quiet background sounds are not being recorded (perhaps to save storage space)
I wondered if there is a way to confirm whether the AGC is enabled and if it can be controlled:
[Automatic Gain Control ](https://developer.android.com/reference/android/media/audiofx/AutomaticGainControl)

Phone Platform | Info
---------------|-----
Phone model | VFD 200
Android API Level | 22
Phone manufacturer | Vodafone
External Mic| [AliExpress](https://www.aliexpress.com/item/Mini-3-5mm-Jack-Microphone-Lavalier-Tie-Clip-Microphones-Microfono-Mic-For-Speaking-Speech-Lectures-1/32839322866.html)

**Comment by timhot** [comment]
Hi David,
Umm, We haven't done anything specifically to mute low level noise - and haven't done any tests.  We have recently made a change on the test server to amplify the recordings, but I'm not sure if that has been deployed to the production server yet, or if it would be a factor (you can still download the original to compare).

The code on the phone samples at highest rate that we thought suitable and relies on the phones encoder - perhaps different phones encode differently - sorry I can't be more specific.

Tim

**Comment by ionise** [comment]
It may be device specific, the dev reference for automatic gain control feature I linked has this paragraph:

> On some devices, an AGC can be inserted by default in the capture path by the platform according to the MediaRecorder.AudioSource used. The application should call AutomaticGainControl.getEnable() after creating the AGC to check the default AGC activation state on a particular AudioRecord session

My VFD 200 phone is literally the cheapest thing I could get my hands on, but I might try and obtain a Spark Lite ZTE BLADE A110 in case it is something with the mic.

**Comment by timhot** [comment]
I've gone back to the code for a look.  No sign of us intentionally using AGC, but as you / the doc's say, it could be happening automatically.  Perhaps we should .setAudioSource to UNPROCESSED as the docs say if you don't then DEFAULT is used which may mean more variation across phones???  However, it also says UNPROCESSED sets it to raw if available!

Code:
MediaRecorder mRecorder = new MediaRecorder();

    // Try to prepare recording.
    try {
        mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        mRecorder.setOutputFile(filePath);

            // Sampling configuration
            mRecorder.setAudioChannels(1);
            mRecorder.setAudioSamplingRate(16000);

            // Encoding configuration
            mRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4); // MPEG_4 added in API 1
            mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC); // AAC added in API 10
            mRecorder.setAudioEncodingBitRate(256000);

        mRecorder.prepare();
......
 mRecorder.start();
....
  Thread.sleep(recordTimeSeconds * 1000);
....

 // Stop recording.
    mRecorder.stop();

    mRecorder.reset();
    mRecorder.release();

**Comment by ionise** [comment]
I don't want to take you off spending time on more important things if it just turns out I have a crappy mic or the TRRS connector isn't compatible. 

I think you can park it for now unless its real quick to build me an APK I can test with MIC set to UNPROCESSED (I'm not currently geared up to roll my own). 

I'll try and get myself the Spark reference device and retest or get my PC set up to build Android things. I can see the part in "RecordAndUpload.java" you refer to so once I can compile it myself I can have a play.

**Comment by timhot** [comment]
Sorry - I'm not going to have time for quite a while.  But it is definitely something I will look at.

Tim
________________________________

**Comment by mjs** [comment]
It looks like whether or not AGC is enabled depends on the specific phone model and attached audio hardware.

https://stackoverflow.com/questions/14377481/how-avoid-automatic-gain-control-with-audiorecord

One solution would be to have some logic which attempts to disable AGC depending on the phone model or which features are available.

I've seen a few sources which indicate that the VOICE_RECOGNITION audio source may lead to AGC being disabled but I'm not sure what else this source does to the sound.

https://forum.xda-developers.com/showthread.php?t=1042051

**Comment by ionise** [comment]
Just an update. I have got a Spark ZTE Blade L110 and installed v1.2 - I attached the same mic as I was using on the VFD 200 and this has much clearer recordings.

**Comment by mjs** [comment]
@ionise that's great to know. Thanks for the update. 

I guess one way to ensure decent audio quality is to only use "known good" phones. It's still worth exploring what can be done in software (disabling AGC etc) because that might increase the range of hardware we can use.

**Comment by timhot** [comment]
I've had a look at this some more:

Our code uses MediaRecorder rather than AudioRecord which Menno's link above discussed.  What is the difference? According to -

https://stackoverflow.com/questions/5886872/android-audiorecord-vs-mediarecorder-for-recording-audio

Basically MediaRecorder does a lot of the work for you.  It does have the options of setting AudioSource
 
https://developer.android.com/reference/android/media/MediaRecorder.AudioSource 

I quote "Defines the audio source. An audio source defines both a default physical source of audio signal, and a recording configuration."

Our code was using 'MIC' for the AudioSource and I did some tests using 'UNPROCESSED' I quote "Microphone audio source tuned for unprocessed (raw) sound if available, behaves like DEFAULT otherwise."

Using the reference phone/mic setup I could hear (and see on plots) no difference.  Which is good news for our setup.  I'll look at adding the ability to select any of the options from within the app in case it helps with other phones.

This forum does not allow me to upload the audio files - but I can send them to you if you what to check my ears :-)

Tim

**Comment by timhot** [comment]
I've added the ability to change the settings.  I've made a 2 second recording of 'silence' using each of the 6 available settings - see attached pdf.  Unfortunately I forgot to use an external mic, so these are using the phones mic.  I also Amplified the recodings using Audacity (otherwise you could see much).

I don't know what to make of it! I can send you the audio files if you want.

Tim


[Audio settings comparison.pdf](https://github.com/TheCacophonyProject/cacophonometer/files/2785921/Audio.settings.comparison.pdf)

**Comment by mjs** [comment]
The plots might look more different than they really are because of those peaks which might have been due to some background noise or the phone being moved or something.

**Comment by timhot** [comment]
Good point about the peaks.  I'm almost ready to send you the modified app David so you'll be able to do some testing if you want .....

**Comment by timhot** [comment]
Hi David,

Beta test app here if you want to try it - has the ability to choose AudioSource setting.

https://github.com/TheCacophonyProject/cacophonometer/releases/tag/1.3.4Beta

**Comment by ionise** [comment]
I have installed the latest beta test on the Vodafone VFD-200 and I'll let it make and upload some recordings until the battery is exhausted. I may capture some vocalisations from the builders down the road when they are greeting each other or a female walks past.
This link is for a recording that was made last year on the previous version for comparison - i don't know why I didn't already share one to illustrate the problem - the very beginning of the recording you can hear some whitenoise/wind but it is quite choppy where presumably the ADC is clipping the audio.  https://www.dropbox.com/s/taa6kqr5axk7kx1/20181125-143221.m4a?dl=0

**Comment by timhot** [comment]
I couldn't hear much - but what I could, also reminded me of the interference that I have seen when the phone is uploading at the same time as doing a recording.  That should NOT normally happen as the code does an upload after a recording has happened, and so should have finished uploading before the next recording starts.  You'll be the first to use v1.4.4Beta, so I'm keen to hear any feedback :-)

**Comment by ionise** [comment]
I'm working my way through the different recording modes but have some early feedback:
The page where you can select the different modes doesn't quite fit on the screen of the VFD-200, I think the last option is "VOICE_RECOGNITION" but this has fallen off the bottom of the screen and can't scroll down to see it but I can just see the top of the option and select it. ( Shall I make a new issue for this?)
I have started with MIC and progressing though UNPROCESSED and VOICE_COMMUNICATION
So far the only mode with any success is MIC, for the others the recordings don't seem to be made and I end up with a small empty m4a file (a few k/bytes in size) uploaded to the browser (Here's one: https://www.dropbox.com/s/klf7qqb2rmznwaq/20190129-155007.m4a?dl=0)
I'm almost concluded that telling the VFD-200 which mode to use is unsupported. I will also run the version on the ZTE Blade L110 and confirm that there are no ill effects. 
(I'm yet to try CAMCORDER )

**Comment by ionise** [comment]
It looks like the UNPROCESSED option doesnt work on a VFD-200.
I managed to figure out get some logging from the USB port to view via Android Studio (forgive my ignorance if there is a better way to do this, logging is set to Verbose so a lot of stuff spews up the screen,  I have selected blocks which seem to correspond with actions taken in the app but there looks like there is some ambient activity that doesn't relate)

Below are some logs for MIC mode which makes a recording but with the clipped audio and further down there is a log from a recording in UNPROCESSED mode which results in the empty recording being uploaded to the server. 

The **MIC** mode I see these lines in the log when I select Record Now in the Test Record screen:

> 01-29 17:39:55.094 503-518/? D/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{36ba69dd u0 null}, [background], remain = -1, in 101ms
> 01-29 17:39:55.094 14039-14256/nz.org.cacophonoy.cacophonometer.dev D/nz.org.cacophony.cacophonometer.MainThread: MainThread 1
> 01-29 17:39:55.114 14039-14256/nz.org.cacophonoy.cacophonometer.dev D/nz.org.cacophony.cacophonometer.RecordAndUpload: typeOfRecording is recordNowButton
> 01-29 17:39:55.144 14039-14054/nz.org.cacophonoy.cacophonometer.dev I/art: Background partial concurrent mark sweep GC freed 19579(1372KB) AllocSpace objects, 1(16KB) LOS objects, 21% free, 7MB/9MB, paused 1.098ms total 187.011ms
> 01-29 17:39:55.154 14039-14256/nz.org.cacophonoy.cacophonometer.dev I/nz.org.cacophony.cacophonometer.Util: sd card IS detected
> 01-29 17:39:55.174 503-641/? D/ThermalSensor: fetchSensorTemp,curr=42162
> 01-29 17:39:55.174 503-641/? D/ThermalSensor: sensor_cpu sensor,currtemp=42162
> 01-29 17:39:55.174 503-641/? D/ThermalSensor: cpu sensor->setCurrTemp:exit synchronized
> 01-29 17:39:55.184 191-586/? W/StagefrightRecorder: Intended audio encoding bit rate (256000) is too large and will be set to (96000)
> 01-29 17:39:55.184 191-586/? I/AudioPolicyManager: getInputForAttr() source 1, samplingRate 16000, format 1, channelMask 10,session 55, flags 0
> 01-29 17:39:55.184 191-586/? I/AudioPolicyManager: getDeviceForInputSource()input source 1, device 80000004
> 01-29 17:39:55.184 191-586/? V/AudioPolicyManager: DeviceVector::getDevice() for type 80000004 address  found 0xb83e91e0
> 01-29 17:39:55.184 191-586/? W/audio_hw_primary: [TH], adev_open_input_stream,devices=0x80000004,sample_rate=16000, channel_count=1
> 01-29 17:39:55.184 191-586/? W/audio_hw_primary: Successfully, adev_open_input_stream.
> 01-29 17:39:55.184 191-14259/? I/AudioFlinger: AudioFlinger's thread 0xb84b9ad8 ready to run
> 01-29 17:39:55.184 191-14259/? I/audio_hw_primary: do_input_standby, standby=1, in_devices=0x80000004
> 01-29 17:39:55.184 191-14259/? D/audio_hw_primary: do_input_standby out
> 01-29 17:39:55.184 191-586/? V/AudioPolicyManager: getInputForAttr() returns input type = -1297794648
> 01-29 17:39:55.184 191-14259/? I/audio_hw_primary: do_input_standby, standby=1, in_devices=0x80000004
> 01-29 17:39:55.184 191-14259/? D/audio_hw_primary: do_input_standby out
> 01-29 17:39:55.184 191-586/? W/AudioFlinger: acquireAudioSessionId() unknown client 14039 for session 55
> 01-29 17:39:55.184 191-14260/? I/OMXCodec: findMatchingCodecs, componentName: OMX.google.aac.encoder, matchIndex: 13, flag: 0x0
> 01-29 17:39:55.194 191-14260/? I/MediaCodec: MediaCodec will operate in async mode
> 01-29 17:39:55.194 191-586/? I/MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: 96000 bps and the estimated moov size 3072 bytes
> 01-29 17:39:55.204 191-14257/? I/MediaCodecSource: MediaCodecSource (audio) starting
> 01-29 17:39:55.204 191-14264/? V/AudioPolicyManager: startInput() input 56
> 01-29 17:39:55.204 191-14264/? I/AudioPolicyManager: getDeviceForInputSource()input source 1, device 80000004
> 01-29 17:39:55.204 191-14264/? I/AudioPolicyManager: getNewInputDevice() selected device 80000004
> 01-29 17:39:55.204 191-14264/? I/AudioPolicyManager: setInputDevice() input is 56, device is 80000004, force is 1.
> 01-29 17:39:55.204 191-14264/? V/AudioPolicyManager: DeviceVector::refreshTypes() mDeviceTypes 80000004
> 01-29 17:39:55.204 191-14264/? V/AudioPolicyManager: DeviceVector::getDevicesFromType() for type 80000004 found 0xb83e72c8
> 01-29 17:39:55.204 191-14259/? W/audio_hw_primary: [in_set_parameters], kvpairs=input_source=1;routing=-2147483644 in_devices:0x80000004 mode:0 
> 01-29 17:39:55.204 191-14259/? E/audio_hw_primary: AUDIO_PARAMETER_STREAM_INPUT_SOURCE in_set_parameters val 1
> 01-29 17:39:55.204 191-14259/? I/audio_hw_primary: requested_rate 16000,pop_mute_bytes 6400 frame_size 2
> 01-29 17:39:55.204 191-14264/? I/AudioPolicyManager: setInputDevice() createAudioPatch returned 11 patchHandle 0
> 01-29 17:39:55.204 191-14264/? V/AudioPolicyManager: AudioPolicyManager::startInput() input source = 1
> 01-29 17:39:55.204 191-14257/? I/MediaCodecSource: MediaCodecSource (audio) started
> 01-29 17:39:55.214 191-14259/? D/audio_hw_primary: into in_read1: start: in->is_voip is 0, voip_state is 0 in_devices is 80000004
> 01-29 17:39:55.214 191-14259/? W/audio_hw_primary: start_input_stream in mode:0 devices:80000004 call_start:0, is_voip:0, is_bt_sco:0
> 01-29 17:39:55.214 191-14259/? E/audio_hw_primary: select_devices_signal starting... adev->out_devices 0x2 adev->in_devices 0x80000004
> 01-29 17:39:55.214 191-14259/? I/audio_hw_primary: select_devices_signal finished.
> 01-29 17:39:55.214 191-14259/? E/audio_hw_primary: start_input_stream pcm_open_0
> 01-29 17:39:55.214 191-14259/? W/audio_hw_primary: rec_mode(3), sample_rate(16000)
> 01-29 17:39:55.214 191-14259/? W/audio_hw_primary: extendArraySize=118, eq_size=52, dp_size=38
> 01-29 17:39:55.214 191-14259/? I/audio_hw_primary: record process module created is successful.
> 01-29 17:39:55.214 191-14259/? E/audio_hw_primary: start_input,channels=1,peroid_size=1280, peroid_count=2,rate=16000
> 01-29 17:39:55.214 191-14259/? E/audio_hw_primary: start input stream out
> 01-29 17:39:55.214 191-548/? I/audio_hw_primary: do_select_devices E
> 01-29 17:39:55.214 191-548/? I/audio_hw_primary: Not to change mute: 0
> 01-29 17:39:55.214 191-548/? I/audio_hw_primary: Changing out_devices: from (0x00000002) to (0x00000002)
> 01-29 17:39:55.214 191-548/? I/audio_hw_primary: Changing in_devices: from (0x7ffffffb) to (0x80000004)
> 01-29 17:39:55.214 191-548/? W/audio_hw_primary: vb_control_parameters.c hp_pa_delay_config 0x0 pa_config:0x10(0x10, 0), 0x110(fm)(0x110, 0),  hpPaConfig:0x0(0x0, 0), 0x0(fm)(0x0, 0)
> 01-29 17:39:55.314 191-548/? W/audio_hw_primary: SetAudio_PaConfig_by_devices out, out_devices:0x2, in_devices:0x80000004
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'SPKL Mixer DACLSPKL Switch'.0 to 1
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'SPKL Mixer DACRSPKL Switch'.0 to 1
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'Speaker Function'.0 to 1
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'Aux Mic Function'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'ADCL Mixer AuxMICADCL Switch'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'ADCR Mixer AuxMICADCR Switch'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'HP Mic Function'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'ADCL Mixer HPMICADCL Switch'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'ADCR Mixer HPMICADCR Switch'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'Digital FM Function'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'AD IISMUX'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'DA1 ADDFM MUX'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'DA0 ADDFM MUX'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'HeadPhone Function'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'HPL Mixer DACLHPL Switch'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'HPR Mixer DACRHPR Switch'.0 to 0
> 01-29 17:39:55.314 191-548/? V/audio_hw_primary: Set 'Earpiece Function'.0 to 0
> 01-29 17:39:55.314 191-548/? I/vb_effect: s_cur_out_devices(0x00000002), s_cur_in_devices(0x80000004)
> 01-29 17:39:55.314 191-548/? I/vb_effect: profile is Handsfree, ret=0
> 01-29 17:39:55.314 191-548/? W/audio_hw_primary: GetAudio_gain_by_devices, outmode:3 inmode:3,indev:0x80000004, outdev:0x2
> 01-29 17:39:55.314 191-548/? W/audio_hw_primary: vb_control_parameters.c pa_config:0x10(0x10, 0), 0x110(fm)(0x110, 0),  hpPaConfig:0x0(0x0, 0), 0x0(fm)(0x0, 0)
> 01-29 17:39:55.314 191-548/? W/audio_hw_primary: vb_control_parameters.c GetAudio_outpga_nv, dac_pga_gain_l:0x801807c6 fm_pga_gain_l:0x245 fm_pga_gain_r:0x245 vol_level:0x1 
> 01-29 17:39:55.314 191-548/? W/audio_hw_primary: GetAudio_inpga_nv, adc_pga_gain_l:0x9030 device:0x80000004 vol_level:0x1
> 01-29 17:39:55.314 191-548/? D/audio_pga: 'speaker-l' apply
> 01-29 17:39:55.314 191-548/? D/audio_pga: 'speaker-r' apply
> 01-29 17:39:55.314 191-548/? D/audio_pga: 'capture-l' apply
> 01-29 17:39:55.314 191-548/? D/audio_pga: 'capture-r' apply
> 01-29 17:39:55.314 191-548/? W/audio_hw_primary: SetAudio_gain_by_devices out, out_devices:0x2, in_devices:0x80000004
> 01-29 17:39:55.314 191-548/? I/audio_hw_primary: do_select_devices X
> 01-29 17:39:55.314 191-548/? I/audio_hw_primary: stream_routing_thread looping done.
> 01-29 17:39:55.314 191-548/? I/audio_hw_primary: stream_routing_thread looping now...
> 01-29 17:39:55.394 191-14259/? E/audio_hw_primary:   peter: normal read 1 in
> 01-29 17:39:55.394 191-14259/? E/audio_hw_primary: set mute in_read bytes 2560 in->pop_mute_bytes 6400
> 01-29 17:39:55.394 191-14259/? D/audio_hw_primary: into in_read1: start: in->is_voip is 0, voip_state is 0 in_devices is 80000004
> 01-29 17:39:55.394 191-14265/? I/MPEG4Writer: setStartTimestampUs: 195831
> 01-29 17:39:55.394 191-14265/? I/MPEG4Writer: Earliest track starting time: 195831
> 01-29 17:39:55.474 191-14259/? E/audio_hw_primary:   peter: normal read 1 in
> 01-29 17:39:55.474 191-14259/? E/audio_hw_primary: set mute in_read bytes 2560 in->pop_mute_bytes 3840
> 01-29 17:39:55.474 191-14259/? D/audio_hw_primary: into in_read1: start: in->is_voip is 0, voip_state is 0 in_devices is 80000004
> 01-29 17:39:55.554 191-14259/? E/audio_hw_primary:   peter: normal read 1 in
> 01-29 17:39:55.554 191-14259/? E/audio_hw_primary: set mute in_read bytes 2560 in->pop_mute_bytes 1280
> 01-29 17:39:55.554 191-14259/? D/audio_hw_primary: into in_read1: start: in->is_voip is 0, voip_state is 0 in_devices is 80000004
> 01-29 17:39:55.634 191-14259/? E/audio_hw_primary:   peter: normal read 1 in
****SNIP****


If I select **UNPROCESSED** mode then it fails to record anything and these lines show in the log; in particular: _01-29 17:32:53.853 14039-14097/nz.org.cacophonoy.cacophonometer.dev E/MediaRecorder: start failed: -38_

> 1-29 17:32:53.763 14039-14097/nz.org.cacophonoy.cacophonometer.dev D/nz.org.cacophony.cacophonometer.MainThread: MainThread 1
> 01-29 17:32:53.773 14039-14097/nz.org.cacophonoy.cacophonometer.dev D/nz.org.cacophony.cacophonometer.RecordAndUpload: typeOfRecording is recordNowButton
> 01-29 17:32:53.793 14039-14054/nz.org.cacophonoy.cacophonometer.dev I/art: Background sticky concurrent mark sweep GC freed 8582(528KB) AllocSpace objects, 4(64KB) LOS objects, 12% free, 4MB/4MB, paused 3.723ms total 132.965ms
> 01-29 17:32:53.813 14039-14097/nz.org.cacophonoy.cacophonometer.dev I/nz.org.cacophony.cacophonometer.Util: sd card IS detected
> 01-29 17:32:53.853 191-586/? I/MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: 0 bps and the estimated moov size 3072 bytes
> 01-29 17:32:53.853 191-586/? E/MPEG4Writer: No source added
> 01-29 17:32:53.853 191-586/? D/MPEG4Writer: Stopping writer thread
> 01-29 17:32:53.853 191-14099/? D/MPEG4Writer: 0 chunks are written in the last batch
> 01-29 17:32:53.853 191-586/? D/MPEG4Writer: Writer thread stopped
> 01-29 17:32:53.853 14039-14097/nz.org.cacophonoy.cacophonometer.dev E/MediaRecorder: start failed: -38
> 01-29 17:32:53.853 14039-14097/nz.org.cacophonoy.cacophonometer.dev E/nz.org.cacophony.cacophonometer.RecordAndUpload: mRecorder.start null
> 01-29 17:32:53.853 14039-14097/nz.org.cacophonoy.cacophonometer.dev I/nz.org.cacophony.cacophonometer.Util: sd card IS detected
> 01-29 17:32:53.863 601-7419/? D/BatteryMeterView: TimerTask :run --level = 99
> 01-29 17:32:53.863 601-601/? D/BatteryMeterView: handleMessage
> 01-29 17:32:53.863 14039-14097/nz.org.cacophonoy.cacophonometer.dev I/nz.org.cacophony.cacophonometer.Util: sd card IS detected
> 01-29 17:32:53.863 601-7420/? D/BatteryMeterView: TimerTask :run --level = 99
> 01-29 17:32:53.863 601-7421/? D/BatteryMeterView: TimerTask :run --level = 99
> 01-29 17:32:53.873 601-601/? D/BatteryMeterView: handleMessage
> 01-29 17:32:53.883 601-601/? D/BatteryMeterView: handleMessage
> 01-29 17:32:53.923 14039-14097/nz.org.cacophonoy.cacophonometer.dev D/LoadClassManager:  loadClass
> 01-29 17:32:53.933 14039-14097/nz.org.cacophonoy.cacophonometer.dev D/LoadClassManager: --------------------------
> 01-29 17:32:53.933 14039-14097/nz.org.cacophonoy.cacophonometer.dev D/LoadClassManager: --------------------------
> 01-29 17:32:54.323 14039-14097/nz.org.cacophonoy.cacophonometer.dev I/nz.org.cacophony.cacophonometer.Server: SERVER REPLIED:

Other modes seem to make a recording, but still have the clipped audio the same as for MIC mode.

I think I would conclude the VFD-200 is just not a suitable device to make recordings.

**Comment by timhot** [comment]
Did you see that it said:
 "W/StagefrightRecorder: Intended audio encoding bit rate (256000) is too large and will be set to (96000)"

Having a reduced encoding rate may be a cause of the clipping?

Thanks for all the testing - and I agree, it looks like the VFD-200 isn't going to play ball.
