### ISSUE TITLE
Enable recordings on "test recordings" page if required

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophonometer#20]
If recordings are disabled then you have to go out and then return to the screen - which is painful.

Given that there is limited space on the screen, if recordings are disabled and the user requests a test, pop up a warning to let them know that recordings are being enabled. Could recordings be disabled again the test?

**Comment by timhot** [comment]
I've started to work on this.  
I think the easiest/best(?) fix is to just have the code ignore the fact that recording is disabled when the record button is pressed - the user knows that they are doing a recording - so the idea of app having the ability to prevent inadvertent recording does not apply in this case.

**Comment by timhot** [comment]
This has been implemented.  What is the protocol for who closes the issue?

**Comment by mjs** [comment]
Go for it if you're sure it's been done
