### ISSUE TITLE
Adding a new group - If there is an error, the group stays in the list

### ISSUE THREAD

**Issue by timhot** [TheCacophonyProject/cacophonometer#32]
When adding a new group, if there is an error adding the group, a message is displayed BUT the group stays in the group list - it shouldn't.

Perhaps the group should not be added to the list until after confirmation is received back from the server.

**Comment by timhot** [comment]
The sortGroups method calls adapter.notifyDataSetChanged(), but I'm not seeing the group list being updated in the user display - can you check please.

**Comment by jackodsteel** [comment]
> The sortGroups method calls adapter.notifyDataSetChanged(), but I'm not seeing the group list being updated in the user display - can you check please.

You're right, and my bad for not testing thoroughly enough. Fixed up in my next PR :)
