### ISSUE TITLE
SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by timhot** [TheCacophonyProject/cacophonometer#39]
This error occurs when attempting to sign in using a Huawei P7-L11 running Android OS 4.4.2 (19)

04-18 10:24:40.107 28763-28989/nz.org.cacophony.birdmonitor.dev E/nz.org.cacophony.birdmonitor.Server: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x74a276c0: Failure in SSL library, usually a protocol error
    error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:741 0x717f9d74:0x00000000)
04-18 10:24:58.417 599-635/? E/InputDispatcher: channel '447693c8 nz.org.cacophony.birdmonitor.dev/nz.org.cacophony.birdmonitor.SetupWizardActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

I haven't seen it on the ZTE BLADE A110 running Android OS 5.1 (22) nor the Nokia 1 running Android OS 8.1 (27) 

ps At first it looked liked that this bug was new, as I thought all was OK with version 1.3.9 (first App Store release), but when I've gone back to check, it now shows the same bug.  Perhaps a change on the server??

**Comment by mjs** [comment]
Nothing has changed on the server.  It looks like the old SSL/TLS support on the old Android running on this phone is having problems.

You could try enabling TLSv1.2 as per this article: https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/

**Comment by jackodsteel** [comment]
This may be fixed by PR #37 as I switched to `OkHttpClient` in that fix. Seems to have fixed a related issue I was seeing on old Android versions.

If it is, worth checking if we're getting the same issue on uploading an audio recording, as that's the only thing still using the standard HTTP library. If so it might be worth updating that to use OkHttp too.

**Comment by timhot** [comment]
It has been fixed :-)

And yes, uploading a recording is causing an error.  I'll assign this to you to finish off. But I don't seem to be able to assign it to you?

**Comment by jackodsteel** [comment]
Not sure, maybe you can only assign things to collaborators? Not sure. No worries, fixed now.

**Comment by mjs** [comment]
@jackodsteel You should have an invite to join the Contributors group which should give you more permissions.
