### ISSUE TITLE
Add to F-Droid Store

### ISSUE THREAD

**Issue by gferraro** [TheCacophonyProject/cacophonometer#58]
Add Bird Monitor to the F-Droid store

**Comment by licaon-kter** [comment]
Any chance to add a FOSS flavour without closed source libs like Crashlytics or Firebase?

Right now F-Droid is stuck at v1.6.5

**Comment by gferraro** [comment]
Hi, sorry but at the moment, we will be continuing forward without F-Droid. If you'd like to get the latest version you will be able to find it on the play store or via github releases (https://github.com/TheCacophonyProject/bird-monitor/releases)

**Comment by licaon-kter** [comment]
That's unfortunate :(
